version: 1.1.1+{build}
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: false
branches:
  only:
  - master
before_build:
- nuget restore
build:
  verbosity: minimal
  publish_nuget: false
  publish_nuget_symbols: false

